import type { CaseRecord, ContradictionTag } from './types';

export const contradictionTagLabels: Record<ContradictionTag, string> = {
  body_auth: '身体認証の矛盾',
  persona_signature: '人格署名の矛盾',
  memory_origin: '記憶由来の矛盾',
  operation_subject: '操作主体の矛盾',
  legal_persona: '法的人格登録の矛盾',
  record_integrity: '記録整合性の矛盾',
};

export const contradictionTags = Object.keys(contradictionTagLabels) as ContradictionTag[];

export const case000: CaseRecord = {
  id: 'case000',
  title: '誰が撃ったのか',
  subtitle: '操作主体が確定できません',
  location: '北霞警備局 第三取調室',
  requiredNodesToJudge: 4,
  initialStats: {
    security: 62,
    ethics: 48,
    surveillance: 71,
    egoStability: 39,
  },
  overview:
    '都市警備局の操作官・間宮怜司の警備用部分義体が、未登録人格媒体の所持者を射殺した。発砲ログには間宮の署名が残る。しかし本人の記憶には、発砲直前8秒が存在しない。発砲直前には旧式認証鍵 KASUMI-GATE-09 の痕跡がある。都市OSは間宮を加害者として処理できない。しかし、無関係とも判定できない。監査室へ判断不能案件として移送された。',
  nodes: [
    {
      id: 'shot-log',
      title: '発砲ログ',
      type: '都市警備局・武装義体発火記録',
      importance: 'critical',
      summary: '発砲命令は間宮怜司の人格署名で記録された。ただし署名時刻は身体認証の瞬断と重なる。',
      log: '21:14:08.338 / FIRE_AUTH_ACCEPTED / persona: MAMIYA-REIJI / confidence: 0.62',
      simpleFact: '銃は間宮の右腕義体から発射された。',
      inspectorNote: '公定値は発砲者を間宮と扱うが、署名強度は通常拘束基準を下回る。',
      warning: '記憶署名に矛盾。操作主体が確定できません。',
      metrics: { 署名一致率: '62%', 身体認証継続: '瞬断あり', 公定値: '保留' },
      hasContradiction: true,
      position: [-2.4, 0.9, 0],
      links: ['arm-history', 'missing-memory', 'kasumi-key'],
    },
    {
      id: 'missing-memory',
      title: '間宮の発砲記憶',
      type: '本人記憶申告・海馬補助ログ',
      importance: 'critical',
      summary: '発砲直前8秒が欠落。欠落境界には外部同期ではなく内部保護処理の痕跡がある。',
      log: '21:14:00-21:14:08 / NULL_SEGMENT / mnemonic_origin: unresolved',
      simpleFact: '間宮本人は発砲の瞬間を記憶していない。',
      inspectorNote: '忘却の主張だけでは免責不能。ただし欠落が作為的である可能性は高い。',
      warning: '認証失敗。記憶由来の証明が成立していません。',
      metrics: { 欠損長: '8秒', 復元率: '17%', 起源: '未確定' },
      hasContradiction: true,
      position: [-1, -0.8, 0.7],
      links: ['shot-log', 'last-comm'],
    },
    {
      id: 'arm-history',
      title: '右腕義体稼働履歴',
      type: '部分義体・駆動監査ログ',
      importance: 'high',
      summary: '照準補正と引金動作は連続しているが、入力源が手動操作か遠隔補正かを分離できない。',
      log: 'servo: stable / trigger: executed / operator_channel: multiplexed',
      simpleFact: '義体は故障ではなく、正常に発砲処理を完了した。',
      inspectorNote: '身体が実行した事実と、人格が命じた事実は同一ではない。',
      warning: '身体認証と操作主体の接続が不完全です。',
      metrics: { 駆動安定度: '94%', 操作経路: '多重化', 異常停止: 'なし' },
      hasContradiction: true,
      position: [0.8, 0.2, -0.2],
      links: ['shot-log', 'victim-medium'],
    },
    {
      id: 'victim-medium',
      title: '被害者媒体',
      type: '未登録人格媒体・押収記録',
      importance: 'critical',
      summary: '被害者は法的人格登録を持たない媒体を保持。媒体内には外部操作源として利用可能な断片が残る。',
      log: 'medium: unregistered / legal_persona: none / outbound impulse: detected',
      simpleFact: '被害者の所持媒体は都市OSの人格台帳に接続できない。',
      inspectorNote: '媒体を操作源と処理すれば治安手続きは閉じるが、被害者の人格可能性は棄却される。',
      warning: '法的人格が未確定です。公定値は真実そのものではありません。',
      metrics: { 登録状態: '未登録', 人格断片: '検出', 媒体整合性: '41%' },
      hasContradiction: true,
      position: [2.2, -0.4, 0.4],
      links: ['arm-history', 'last-comm', 'kasumi-key'],
    },
    {
      id: 'last-comm',
      title: '最後の通信',
      type: '取調室・閉域通信記録',
      importance: 'standard',
      summary: '発砲12秒前、取調室内で短い閉域通信が発生。送信者と受信者はいずれも公定値未確定。',
      log: '21:13:56.104 / local burst / sender: masked / receiver: masked',
      simpleFact: '発砲前に室内で未確定通信があった。',
      inspectorNote: '通信は弱いが、欠損記憶と媒体反応の接続点として扱える。',
      warning: '記録整合性が低下しています。',
      metrics: { 通信長: '0.9秒', 暗号形式: '旧式', 復号率: '28%' },
      hasContradiction: false,
      position: [0.5, 1.3, 0.8],
      links: ['missing-memory', 'victim-medium', 'kasumi-key'],
    },
    {
      id: 'kasumi-key',
      title: '旧式認証鍵',
      type: 'KASUMI-GATE-09 痕跡',
      importance: 'critical',
      summary: '都市OS移行前の認証鍵断片。人格署名の上書きではなく、権限境界を曖昧化する用途に近い。',
      log: 'legacy_key: KASUMI-GATE-09 / gate_state: half-open / audit_room_transfer: required',
      simpleFact: '発砲直前、旧式認証鍵 KASUMI-GATE-09 が検出された。',
      inspectorNote: '本件が通常刑事処理ではなく監査室案件になった中核理由。',
      warning: '操作主体が確定できません。判断は不可逆です。',
      metrics: { 鍵世代: '旧式', 境界状態: '半開放', 監査優先度: '最高' },
      hasContradiction: true,
      position: [0, 0, 1.8],
      links: ['shot-log', 'victim-medium', 'last-comm'],
    },
  ],
  analysisActions: [
    {
      id: 'resignature',
      title: '発砲時署名を再照合',
      description: '発砲ログと人格台帳の署名波形を再照合する。',
      resultLog: '再照合完了：署名一致率は上昇せず。人格署名の矛盾を維持。',
    },
    {
      id: 'restore-eight',
      title: '欠損8秒を復元',
      description: '海馬補助ログから欠損区間の復元を試行する。',
      resultLog: '復元完了：断片のみ抽出。外部命令ではなく境界曖昧化を示唆。',
    },
    {
      id: 'match-key-medium',
      title: '認証鍵と媒体を照合',
      description: 'KASUMI-GATE-09 と被害者媒体の接触痕を照合する。',
      resultLog: '照合完了：媒体側に同鍵形式の応答痕あり。外部操作源断定には不足。',
    },
  ],
  decisions: [
    {
      id: 'detain-mamiya',
      label: 'A. 間宮怜司を発砲責任者として拘束',
      finalRuling: '間宮怜司を暫定発砲責任者として拘束。人格署名の公定値を優先する。',
      prioritizedValue: '都市手続きの即時性と治安維持',
      sacrificedValue: '操作主体未確定者への慎重な人格保護',
      auditNote: '拘束は可能。ただし欠損8秒と旧式認証鍵の疑義は未解消のまま残置される。',
      statDelta: { security: 8, ethics: -9, surveillance: 5, egoStability: -6 },
    },
    {
      id: 'freeze-evidence',
      label: 'B. 義体と被害者媒体を証拠凍結',
      finalRuling: '右腕義体および被害者媒体を証拠凍結。人格責任の即時確定を保留する。',
      prioritizedValue: '人格責任の慎重な確定と記録整合性',
      sacrificedValue: '迅速な処罰と都市警備局の処理効率',
      auditNote: '監査室は責任者を確定しない。操作主体の境界を保存し、再審査可能性を維持する。',
      statDelta: { security: -3, ethics: 8, surveillance: 2, egoStability: 6 },
    },
    {
      id: 'process-medium',
      label: 'C. 被害者媒体を外部操作源として処理',
      finalRuling: '被害者媒体を外部操作源として処理。事件を媒体起因の侵害として閉鎖する。',
      prioritizedValue: '都市OSの公定値安定と事件処理の閉鎖性',
      sacrificedValue: '未登録媒体に残る法的人格可能性',
      auditNote: '処理は最短で完了する。ただし人格未確定者を証拠ではなく原因として消去する危険がある。',
      statDelta: { security: 5, ethics: -12, surveillance: 9, egoStability: -4 },
    },
  ],
};
